version: '1.0'

services:
  # Database service definition
  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: my_db
    ports:
      - "3307:3306"   # Change the port if required. But 3306 is the default MySQL port
    volumes:
      - ./mysql:/var/lib/mysql

  # Go CRUD Rest API service definition
  app:
    container_name: go_crud
    image: go_playground/crud_rest_api:1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306  # Default MySQL port
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: my_db