name: Go Linter

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.1"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ./crud_rest_api

      - name: Run golangci-lint in dir2
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ./kafka

      - name: Run golangci-lint in dir3
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
          working-directory: ./load_balancer
